### ISSUE TITLE
突然不能执行了

### ISSUE THREAD

**Issue by yuandaijin** [alicfeng/mysql_markdown#10]
/Users/kim/java/mysql_markdown_mac ; exit;                  ✔  910  12:00:02
[1]    41222 killed     /Users/kim/java/mysql_markdown_mac
Saving session...completed

 ~/java  ./mysql_markdown_mac --help                            ✔  909  11:53:58
[1]    40456 killed     ./mysql_markdown_mac --help

**Comment by alicfeng** [comment]
> /Users/kim/java/mysql_markdown_mac ; exit;  ✔  910  12:00:02
> [1] 41222 killed /Users/kim/java/mysql_markdown_mac
> Saving session...completed
> 
> ~/java  ./mysql_markdown_mac --help  ✔  909  11:53:58
> [1] 40456 killed ./mysql_markdown_mac --help


1、下载源码编译运行（ 建议 ）
2、我将会制作 `docker` 镜像 跑容器运行（准备支持）
