### ISSUE TITLE
Dockerfile增加ENTRYPOINT

### ISSUE THREAD

**Issue by he426100** [alicfeng/mysql_markdown#14]
```
FROM alpine:3.7
LABEL Maintainer="AlicFeng <a@samego.com>" \
      Description="mysql_markdown based on golang"

COPY release/mysql_markdown_unix /usr/local/sbin/mysql_markdown

RUN chmod a+x /usr/local/sbin/mysql_markdown && \
    mkdir /data/

WORKDIR /data
ENTRYPOINT [ "/usr/local/sbin/mysql_markdown" ]
CMD [ "--help" ]
```

**Comment by alicfeng** [comment]
> ```
> FROM alpine:3.7
> LABEL Maintainer="AlicFeng <a@samego.com>" \
>       Description="mysql_markdown based on golang"
> 
> COPY release/mysql_markdown_unix /usr/local/sbin/mysql_markdown
> 
> RUN chmod a+x /usr/local/sbin/mysql_markdown && \
>     mkdir /data/
> 
> WORKDIR /data
> ENTRYPOINT [ "/usr/local/sbin/mysql_markdown" ]
> CMD [ "--help" ]
> ```

建议太棒了，好的。
