### ISSUE TITLE
Column排序问题

### ISSUE THREAD

**Issue by sutayaku** [alicfeng/mysql_markdown#2]
序号没有按照OrdinalPosition升序排序，unbuntu18.04下为乱序

**Comment by alicfeng** [comment]
> 序号没有按照OrdinalPosition升序排序，unbuntu18.04下为乱序

好的、非常感激提出此环境下有这种情况，是可以根据OP排序的，目前此段时间无PC在旁，这周内会解决发一个新版，倘若你可以的话修复可以直接push并进行合并。

**Comment by sutayaku** [comment]
已提交修复相关代码，但没太在意代码规范。

**Comment by alicfeng** [comment]
> 已提交修复相关代码，但没太在意代码规范。

不要意思，刚看到合并代码的请求，review了一下，也许是我没有明白的问题的意思，`ORDINAL_POSITION`乱序排序？是的话，可否修改一下`SQL`来解决这个问题呢？

**Comment by sutayaku** [comment]
确实可以，当时为了先解决问题，所以就没在意做法。

**Comment by sutayaku** [comment]
已修改为sql内部排序。
