### ISSUE TITLE
command not found

### ISSUE THREAD

**Issue by wcc4869** [alicfeng/mysql_markdown#7]
![image](https://user-images.githubusercontent.com/22254090/91703142-50292f00-ebac-11ea-9c8b-f5533917d663.png)

**Comment by alicfeng** [comment]
1、在 https://github.com/alicfeng/mysql_markdown/releases 选中对应 `OS` 的文件，解压放置于 `/usr/local/bin` 目录

2、查看 `/usr/local/bin` 下是否存在 `mysql_markdown` 文件

3、检查一下这个文件是否具有可执行权限
