### ISSUE TITLE
mysql_markdown_win

### ISSUE THREAD

**Issue by ghost** [alicfeng/mysql_markdown#8]
mysql_markdown_win.tar.gz 解压后 mysql_markdown_win 未携带扩展名 .exe
且 Windows 未原生支持 tar.gz 格式，需要额外下载解压软件，建议改用 zip 格式

**Comment by alicfeng** [comment]
非常感谢宝贵的建议，`win` 包已经采用 `zip` 替换 `tar.gz`

**Comment by diklios5768** [comment]
现在1.0.5版本，win依旧不带.exe后缀，希望下个版本自动添加一下后缀

**Comment by alicfeng** [comment]
> mysql_markdown_win.tar.gz 解压后 mysql_markdown_win 未携带扩展名 .exe
> 且 Windows 未原生支持 tar.gz 格式，需要额外下载解压软件，建议改用 zip 格式

非常感谢你的建议，win 下的可执行程序已经改成 mysql_markdown_win.exe
